# Generated by Django 5.0.7 on 2024-08-03 17:11

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_book', 'Может создавать книги'), ('can_edit_book', 'Может редактировать книги'), ('can_delete_book', 'Может удалять книги'), ('can_create_author', 'Может создавать автора'), ('can_edit_author', 'Может редактировать автора'), ('can_delete_author', 'Может удалять автора'), ('can_create_publisher', 'Может создавать издателя'), ('can_edit_publisher', 'Может редактировать издателя'), ('can_delete_publisher', 'Может удалять издателя'), ('can_create_genre', 'Может создавать жанр'), ('can_edit_genre', 'Может редактировать жанр'), ('can_delete_genre', 'Может удалять жанр')],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
