# Generated by Django 5.0.7 on 2024-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Эмеил пользователя', max_length=254, unique=True, verbose_name='эмеил'),
        ),
    ]
