services:
  library:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    image: config
    command: /start
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKER_DEBUG=0
    depends_on:
      - redis
      - db
  
  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db
    env_file:
      - .env

  redis:
    image: redis:7.2.5-alpine
    expose:
      - 6379
  
  celery_worker:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: config
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DOCKER_DEBUG=0
    depends_on:
      - redis
      - db

  celery_beat:
    build: 
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: config
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DOCKER_DEBUG=0
    depends_on:
      - redis
      - db
  
  flower:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: config
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5557:5555
    environment:
      - DOCKER_DEBUG=0
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: