#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python manage.py flush --no-input
python manage.py makemigrations
python manage.py migrate
python manage.py loaddata data.json
python manage.py collectstatic --no-input --clear
# python manage.py runserver 0.0.0.0:8000

gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 8
